name: Keep Render Alive

on:
  schedule:
    # Runs every 15 minutes between 9 AM and 4 PM IST (Mon-Fri)
    - cron: "*/5 * * * *"
  workflow_dispatch: # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request to Render app
        run: |
          curl -s https://advance-pdf-cleaning-agent.onrender.com/start
